name: Publish Next Day

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Checkout content branch
        uses: actions/checkout@v4
        with:
          ref: content
          path: temp-content
          fetch-depth: 0

      - name: Find next folder
        run: |
          NEXT=""

          for folder in temp-content/Day*; do
            name=$(basename "$folder")

            if [ ! -d "$name" ]; then
              NEXT=$name
              break
            fi
          done

          echo "Next folder is: $NEXT"